// Code generated by go run make_doctype.go. DO NOT EDIT.

package ebml

import (
	_ "embed"

	"github.com/coding-socks/ebml/schema"
)

//go:embed ebml.xml
var schemaDefinition []byte

var (
	IDEBML                    schema.ElementID = 0x1a45dfa3
	IDEBMLVersion             schema.ElementID = 0x4286
	IDEBMLReadVersion         schema.ElementID = 0x42f7
	IDEBMLMaxIDLength         schema.ElementID = 0x42f2
	IDEBMLMaxSizeLength       schema.ElementID = 0x42f3
	IDDocType                 schema.ElementID = 0x4282
	IDDocTypeVersion          schema.ElementID = 0x4287
	IDDocTypeReadVersion      schema.ElementID = 0x4285
	IDDocTypeExtension        schema.ElementID = 0x4281
	IDDocTypeExtensionName    schema.ElementID = 0x4283
	IDDocTypeExtensionVersion schema.ElementID = 0x4284
	IDVoid                    schema.ElementID = 0xec
	IDCRC32                   schema.ElementID = 0xbf
)

type EBML struct {
	EBMLVersion        uint
	EBMLReadVersion    uint
	EBMLMaxIDLength    uint
	EBMLMaxSizeLength  uint
	DocType            string
	DocTypeVersion     uint
	DocTypeReadVersion uint
	DocTypeExtension   []DocTypeExtension
}

type DocTypeExtension struct {
	DocTypeExtensionName    string
	DocTypeExtensionVersion uint
}
