// +build codegen

// This program generates header.go.

package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"github.com/coding-socks/ebml/internal/schema"
	"golang.org/x/tools/imports"
	"io"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"strings"
)

var header = []byte(`// Code generated by go run make_header.go. DO NOT EDIT.

package ebml

`)

func main() {
	filename := "header.go"
	buf := bytes.NewBuffer(header)

	gen(buf)

	out, err := imports.Process(filename, buf.Bytes(), nil)
	if err != nil {
		log.Fatal(err)
	}

	err = ioutil.WriteFile(filename, out, 0666)
	if err != nil {
		log.Fatal(err)
	}
}

func gen(w io.Writer) {
	root := schema.NewTreeNode(schema.Element{
		Type: schema.TypeMaster,
		Name: "Document",
	})
	for _, fp := range []string{filepath.Join(".", "ebml.xml")} {
		var s schema.Schema
		func() {
			f, err := os.Open(fp)
			if err != nil {
				log.Fatal(err)
			}
			defer f.Close()
			if err := xml.NewDecoder(f).Decode(&s); err != nil {
				log.Fatal(err)
			}
		}()
		for _, el := range s.Element {
			if el.Path == `\(-\)Void` || el.Path == `\(1-\)CRC-32` {
				// TODO: Implement support for Void and CRC-32 tags
				continue
			}
			p := strings.Split(el.Path, `\`)[1:]
			branch := root
			lastIndex := len(p) - 1
			for _, s := range p[:lastIndex] {
				node := branch.Get(s)
				if node == nil {
					node = schema.NewTreeNode(el)
					branch.Put(s, node)
				}
				branch = node
			}
			branch.Put(p[lastIndex], schema.NewTreeNode(el))
		}
	}
	write(w, root.Get("EBML"))
}

func write(w io.Writer, node *schema.TreeNode) {
	if node.El.Type != schema.TypeMaster {
		return
	}
	if node.El.Name == "EBML" {
		fmt.Fprintf(w, "var defaultHeader = EBML{")
		node.VisitAll(func(n *schema.TreeNode) {
			if n.El.Default == "" {
				return
			}
			if n.El.Type == schema.TypeString {
				fmt.Fprintf(w, "\n\t%s: %q,", n.El.Name, n.El.Default)
				return
			}
			fmt.Fprintf(w, "\n\t%s: %s,", n.El.Name, n.El.Default)
		})
		fmt.Fprintf(w, "\n}\n\n")
	}
	fmt.Fprintf(w, "type %s struct {", node.El.Name)
	node.VisitAll(func(n *schema.TreeNode) {
		if n.El.MaxOccurs != 1 {
			fmt.Fprintf(w, "\n\t%s []%s `ebml:\"%s\"`", n.El.Name, schema.ResolveGoType(n.El.Type, n.El.Name), n.El.ID)
			return
		}
		fmt.Fprintf(w, "\n\t%s %s `ebml:\"%s\"`", n.El.Name, schema.ResolveGoType(n.El.Type, n.El.Name), n.El.ID)
	})
	fmt.Fprint(w, "\n}\n\n")
	node.VisitAll(func(n *schema.TreeNode) {
		write(w, n)
	})
}
