name: test

on:
  push:
    branches:
      - 'master'
      - 'next'
  pull_request:
    branches:
      - 'master'
      - 'next'

jobs:
  test-generated-files:
    runs-on: ubuntu-latest

    name: "Test generated files are up to date"

    steps:
      - uses: actions/checkout@v2

      - name: CI Setup
        run: ./.github/commands/ci-setup.sh

      - name: Regenerate files
        run: go generate ./...

      - name: Check git diff
        run: ./.github/commands/fail-on-git-diff.sh
